import { test, expect } from './fixtures/local-auth'

test.skip(!/^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(process.env.BASE_URL || '') || !process.env.LOCAL_E2E_SECRET,
  'Administrator mutation tests require a loopback server and guarded disposable database.')
test.use({ channel: process.env.LOCAL_E2E_CHANNEL || undefined })

for (const width of [1440, 390]) {
  test(`real user role, stale-edit and deactivation workflow at ${width}px`, async ({ page, localAuth }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    const actor = await localAuth.create('ADMIN')
    const target = await localAuth.create('PARENT')
    await localAuth.signIn(actor)
    await page.goto('/admin/users')
    await page.getByLabel('Search users').fill(target.email)
    await page.getByRole('button', { name: 'Search', exact: true }).click()
    const row = page.getByTestId('user-row').filter({ hasText: target.email })
    await row.getByRole('button', { name: 'Change role' }).click()
    await page.getByRole('combobox', { name: 'New role' }).click()
    await page.getByRole('option', { name: 'Trainer', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Update role' })).toBeDisabled()
    await page.getByLabel('Trainer first name').fill('Synthetic')
    await page.getByLabel('Trainer last name').fill('Coach')
    await page.getByRole('button', { name: 'Update role' }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
    await expect(row).toContainText('TRAINER')
    const profile = await localAuth.database.trainerProfile.findUniqueOrThrow({ where: { userId: target.id } })
    expect(profile).toMatchObject({ firstName: 'Synthetic', lastName: 'Coach', approvalStatus: 'PENDING' })

    await localAuth.database.user.update({ where: { id: target.id }, data: { image: '/synthetic-updated.jpg' } })
    await row.getByRole('button', { name: 'Change role' }).click()
    await page.getByRole('combobox', { name: 'New role' }).click()
    await page.getByRole('option', { name: 'Parent', exact: true }).click()
    await page.getByRole('button', { name: 'Update role' }).click()
    await expect(page.getByRole('alert').filter({ hasText: 'Account changed.' })).toBeVisible()
    await expect(row.getByRole('button', { name: 'Change role' })).toBeDisabled()
    await page.getByRole('button', { name: 'Retry', exact: true }).click()
    await expect(row.getByRole('button', { name: 'Change role' })).toBeEnabled()
    await row.getByRole('button', { name: 'Change role' }).click()
    await page.getByRole('combobox', { name: 'New role' }).click()
    await page.getByRole('option', { name: 'Parent', exact: true }).click()
    await page.getByRole('button', { name: 'Update role' }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
    await expect(row).toContainText('PARENT')
    expect((await localAuth.database.trainerProfile.findUniqueOrThrow({ where: { userId: target.id } })).isActive).toBe(false)
    await row.getByRole('button', { name: `Deactivate ${target.email}` }).click()
    await expect(page.getByRole('button', { name: 'Deactivate account', exact: true })).toBeDisabled()
    await page.getByLabel('Reason', { exact: true }).fill('Synthetic browser deactivation')
    await page.screenshot({ path: testInfo.outputPath('account-deactivation.png'), fullPage: true })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
    await page.getByRole('button', { name: 'Deactivate account', exact: true }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
    await expect(page.getByText('No users found', { exact: true })).toBeVisible()
    const closed = await localAuth.database.user.findUniqueOrThrow({ where: { id: target.id } })
    expect(closed.deletedAt).not.toBeNull()
    expect(closed.sessionVersion).toBe(3)
    expect(await localAuth.database.adminAction.count({ where: { targetId: target.id } })).toBe(3)
    await page.getByLabel('Search users').fill(closed.email)
    await page.getByRole('button', { name: 'Search', exact: true }).click()
    await expect(page.getByTestId('user-row').filter({ hasText: closed.email })).toContainText('Deactivated')
    await expect(page.getByTestId('user-row').filter({ hasText: closed.email }).getByRole('button', { name: 'Change role' })).toBeDisabled()
  })

  test(`user list recovers failed loading and blocks repeating an uncertain write at ${width}px`, async ({ page, localAuth }) => {
    await page.setViewportSize({ width, height: 900 })
    const actor = await localAuth.create('ADMIN')
    const target = await localAuth.create('PARENT')
    await localAuth.signIn(actor)
    let failList = true
    let writes = 0
    await page.route('**/api/admin/users**', async route => {
      if (route.request().method() === 'PATCH') {
        writes++
        return route.fulfill({ status: 503, json: { error: 'Unable to confirm this change. Reload before trying again.' } })
      }
      if (failList) return route.fulfill({ status: 503, json: { error: 'Synthetic unavailable database' } })
      return route.continue()
    })
    await page.goto('/admin/users')
    await expect(page.getByRole('alert').filter({ hasText: 'Unable to load users' })).toBeVisible()
    await expect(page.getByText('No users found', { exact: true })).not.toBeVisible()
    failList = false
    await page.getByRole('button', { name: 'Retry', exact: true }).click()
    const row = page.getByTestId('user-row').filter({ hasText: target.email })
    await row.getByRole('button', { name: 'Change role' }).click()
    await page.getByRole('combobox', { name: 'New role' }).click()
    await page.getByRole('option', { name: 'Admin', exact: true }).click()
    await page.getByRole('button', { name: 'Update role' }).click()
    await expect(page.getByRole('alert').filter({ hasText: 'Unable to confirm' })).toBeVisible()
    await expect(row.getByRole('button', { name: 'Change role' })).toBeDisabled()
    expect(writes).toBe(1)
    await page.getByRole('button', { name: 'Retry', exact: true }).click()
    await expect(row.getByRole('button', { name: 'Change role' })).toBeEnabled()
    expect(writes).toBe(1)
    expect((await localAuth.database.user.findUniqueOrThrow({ where: { id: target.id } })).role).toBe('PARENT')
  })
}
